# Generated by Django 5.1.3 on 2024-11-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.PositiveIntegerField()),
                ('peso_inicial', models.FloatField()),
                ('calorias_recomendadas', models.PositiveIntegerField()),
                ('calorias_consumidas', models.PositiveIntegerField()),
                ('calorias_excedentes', models.PositiveIntegerField(default=0)),
                ('peso_calculado', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_calorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('calorias_recomendadas', models.PositiveIntegerField()),
                ('calorias_consumidas', models.PositiveIntegerField()),
                ('calorias_excedentes', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_porciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('porciones_recomendadas', models.PositiveIntegerField()),
                ('porciones_consumidas', models.PositiveIntegerField()),
                ('porciones_excedentes', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
